server:
  port: 8083
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/hmall?useSSL=false&characterEncoding=UTF-8
    username: root
    password: infinity
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    host: localhost # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: itcast # 用户名
    password: 123321 # 密码

mybatis-plus:
  type-aliases-package: com.hmall.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    cn.itcast.feign.client: debug
  pattern:
    dateformat: HH:mm:ss:SSS